/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogTagIndexRouteImport } from './routes/blog/tag/index'
import { Route as BlogTagNameRouteImport } from './routes/blog/tag/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagIndexRoute = BlogTagIndexRouteImport.update({
  id: '/blog/tag/',
  path: '/blog/tag/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagNameRoute = BlogTagNameRouteImport.update({
  id: '/blog/tag/$name',
  path: '/blog/tag/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/tag/$name': typeof BlogTagNameRoute
  '/blog/tag': typeof BlogTagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/tag/$name': typeof BlogTagNameRoute
  '/blog/tag': typeof BlogTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/tag/$name': typeof BlogTagNameRoute
  '/blog/tag/': typeof BlogTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/$slug' | '/blog' | '/blog/tag/$name' | '/blog/tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$slug' | '/blog' | '/blog/tag/$name' | '/blog/tag'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/tag/$name'
    | '/blog/tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogTagNameRoute: typeof BlogTagNameRoute
  BlogTagIndexRoute: typeof BlogTagIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/': {
      id: '/blog/tag/'
      path: '/blog/tag'
      fullPath: '/blog/tag'
      preLoaderRoute: typeof BlogTagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$name': {
      id: '/blog/tag/$name'
      path: '/blog/tag/$name'
      fullPath: '/blog/tag/$name'
      preLoaderRoute: typeof BlogTagNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogTagNameRoute: BlogTagNameRoute,
  BlogTagIndexRoute: BlogTagIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
