/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsSimpleQrcodeRouteImport } from './routes/tools/simple-qrcode'
import { Route as ToolsFlashcardSwPersonRouteImport } from './routes/tools/flashcard-sw-person'
import { Route as ToolsChartMakerRouteImport } from './routes/tools/chart-maker'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogTagIndexRouteImport } from './routes/blog/tag/index'
import { Route as BlogTagNameRouteImport } from './routes/blog/tag/$name'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSimpleQrcodeRoute = ToolsSimpleQrcodeRouteImport.update({
  id: '/tools/simple-qrcode',
  path: '/tools/simple-qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFlashcardSwPersonRoute = ToolsFlashcardSwPersonRouteImport.update({
  id: '/tools/flashcard-sw-person',
  path: '/tools/flashcard-sw-person',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsChartMakerRoute = ToolsChartMakerRouteImport.update({
  id: '/tools/chart-maker',
  path: '/tools/chart-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagIndexRoute = BlogTagIndexRouteImport.update({
  id: '/blog/tag/',
  path: '/blog/tag/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagNameRoute = BlogTagNameRouteImport.update({
  id: '/blog/tag/$name',
  path: '/blog/tag/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/chart-maker': typeof ToolsChartMakerRoute
  '/tools/flashcard-sw-person': typeof ToolsFlashcardSwPersonRoute
  '/tools/simple-qrcode': typeof ToolsSimpleQrcodeRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/blog/tag/$name': typeof BlogTagNameRoute
  '/blog/tag': typeof BlogTagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/chart-maker': typeof ToolsChartMakerRoute
  '/tools/flashcard-sw-person': typeof ToolsFlashcardSwPersonRoute
  '/tools/simple-qrcode': typeof ToolsSimpleQrcodeRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/blog/tag/$name': typeof BlogTagNameRoute
  '/blog/tag': typeof BlogTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/chart-maker': typeof ToolsChartMakerRoute
  '/tools/flashcard-sw-person': typeof ToolsFlashcardSwPersonRoute
  '/tools/simple-qrcode': typeof ToolsSimpleQrcodeRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/blog/tag/$name': typeof BlogTagNameRoute
  '/blog/tag/': typeof BlogTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/tools/chart-maker'
    | '/tools/flashcard-sw-person'
    | '/tools/simple-qrcode'
    | '/blog'
    | '/tools'
    | '/blog/tag/$name'
    | '/blog/tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/tools/chart-maker'
    | '/tools/flashcard-sw-person'
    | '/tools/simple-qrcode'
    | '/blog'
    | '/tools'
    | '/blog/tag/$name'
    | '/blog/tag'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/tools/chart-maker'
    | '/tools/flashcard-sw-person'
    | '/tools/simple-qrcode'
    | '/blog/'
    | '/tools/'
    | '/blog/tag/$name'
    | '/blog/tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToolsChartMakerRoute: typeof ToolsChartMakerRoute
  ToolsFlashcardSwPersonRoute: typeof ToolsFlashcardSwPersonRoute
  ToolsSimpleQrcodeRoute: typeof ToolsSimpleQrcodeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  BlogTagNameRoute: typeof BlogTagNameRoute
  BlogTagIndexRoute: typeof BlogTagIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/simple-qrcode': {
      id: '/tools/simple-qrcode'
      path: '/tools/simple-qrcode'
      fullPath: '/tools/simple-qrcode'
      preLoaderRoute: typeof ToolsSimpleQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/flashcard-sw-person': {
      id: '/tools/flashcard-sw-person'
      path: '/tools/flashcard-sw-person'
      fullPath: '/tools/flashcard-sw-person'
      preLoaderRoute: typeof ToolsFlashcardSwPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/chart-maker': {
      id: '/tools/chart-maker'
      path: '/tools/chart-maker'
      fullPath: '/tools/chart-maker'
      preLoaderRoute: typeof ToolsChartMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/': {
      id: '/blog/tag/'
      path: '/blog/tag'
      fullPath: '/blog/tag'
      preLoaderRoute: typeof BlogTagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$name': {
      id: '/blog/tag/$name'
      path: '/blog/tag/$name'
      fullPath: '/blog/tag/$name'
      preLoaderRoute: typeof BlogTagNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToolsChartMakerRoute: ToolsChartMakerRoute,
  ToolsFlashcardSwPersonRoute: ToolsFlashcardSwPersonRoute,
  ToolsSimpleQrcodeRoute: ToolsSimpleQrcodeRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  BlogTagNameRoute: BlogTagNameRoute,
  BlogTagIndexRoute: BlogTagIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
